config/routes.rb
Rails.application.routes.draw do
  get 'home/about', as: 'about', path:'about'

  get 'home/services', as: 'services', path:'services'

  get 'home/contact', as: 'contact', path:'contact'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  resources :posts, only: [:index, :show, :create, :destroy] do
    resources :comments, only: [:index, :create, :destroy]
  end
  resources :categories
  root 'posts#index'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
      user ||= User.new # guest user (not logged in)
        if user.user?
        can :destroy, Post do |post|
          post.user == user
        end
        can :destroy, Comment do |comment|
          comment.user == user
        end
        can :create, Post
        can :create, Comment
      elsif user.guest?
        can :read, :all
      end
  end
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_and_belongs_to_many :posts
  validates :name, presence: true
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
  validates :title, :body, presence: true
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :comments
  has_and_belongs_to_many :categories
  # validates :title, :body, :category_ids, presence: true
  mount_base64_uploader :image, ImageUploader

  def add_categories(params)
    self.category_ids = params[:category_ids]
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def user?
    role == 'user'
  end

  def guest?
    role == 'guest'
  end

  def can_update
    scope.can?(:update, object)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Can't verify CSRF token authenticity error

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


  # rescue_from CanCan::AccessDenied do |exception|
  #   redirect_to new_user_session_path, :alert => exception.message
  # end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!
  load_resource
  authorize_resource only: [:create, :destroy]
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  respond_to :json

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
    # binding.pry
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id, :name])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.fetch(:category, {})
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  load_resource
  authorize_resource only: [:create, :destroy]
  before_action :set_comment, only: [:show, :edit, :update, :destroy]
  respond_to :json

  def index
    @comments = Comment.where(post_id: params[:post_id])
    # @comments = Comment.find_by(post_id: params[:post_id])
    respond_with(@comments) do |format|
      format.json { render json: @comments }
      format.html
    end
  end

  def create
    @comment = current_user.comments.new(comment_params)
    post = Post.find(params[:post_id])
    respond_to do |format|
      if @comment.save
        format.html { redirect_to post, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: post }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:title, :body, :post_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def about
  end

  def services
  end

  def contact
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: [:create, :destroy]
  load_resource
  authorize_resource only: [:create, :destroy]
  before_action :set_post, only: [:show, :destroy]
  respond_to :json

  def index
    @post = Post.new
    @posts = Post.all.order('created_at DESC')
    respond_with(@posts) do |format|
      format.json { render json: @posts.to_json(include: [ :categories, :user ]) }
      format.html
    end
  end

  def show
    respond_to do |format|
      format.html
      format.json { render json: @post.to_json(:include => :categories) }
    end
  end

  def create
    @post = current_user.posts.new(post_params)
    # @post.add_categories(params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to root_path, notice: 'Post was successfully created.' }
        format.json { render json: @post.to_json(:include => :categories) }
      else
        format.html { render :index }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

    def destroy
      @post.destroy
      respond_to do |format|
        format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    private

    def set_post
      @post = Post.find(params[:id])
    end

    def post_params
      # binding.pry
      params.require(:post).permit(:title, :body, {category_ids: []}, :image)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Categories</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/home/about.html.erb
<h1>About</h1>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>

app/views/home/contact.html.erb
<h1>Contact</h1>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>

app/views/home/services.html.erb
<h1>Services</h1>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>

app/views/layouts/_footer.erb
<!-- Footer -->
<div class="container">
  <footer>
    <div class="row">
      <div class="col-lg-12">
        <p>Copyright &copy; Some Website 2017</p>
      </div>
      <!-- /.col-lg-12 -->
    </div>
    <!-- /.row -->
  </footer>
</div>

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
  ga('create', 'UA-83649468-1', 'auto');
  ga('send', 'pageview');
</script>

app/views/layouts/_header.erb
<!-- Navigation -->
<header class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Home</a>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li>
          <%= link_to 'About', about_path %>
        </li>
        <li>
          <%= link_to 'Services', services_path %>
        </li>
        <li>
          <%= link_to 'Contact', contact_path %>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in?  %>
            <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
        <% else %>
            <li><%= link_to "Sign in", new_user_session_path %></li>
            <li><%= link_to "Sign up", new_user_registration_path %></li>
        <% end %>
      </ul>
    </div>
    <!-- /.navbar-collapse -->
  </div>
  <!-- /.container -->
</header>
<br>
<br>
<br>

app/views/layouts/_sidebar.erb
<!-- Blog Sidebar Widgets Column -->

  <!-- Blog Search Well -->
  <div class="well">
    <h4>Blog Search</h4>
    <div class="input-group">
      <input type="text" class="form-control">
                        <span class="input-group-btn">
                            <button class="btn btn-default" type="button">
                                <span class="glyphicon glyphicon-search"></span>
                        </button>
                        </span>
    </div>
    <!-- /.input-group -->
  </div>

  <!-- Blog Categories Well -->
  <div class="well">
    <h4>Blog Categories</h4>
    <div class="row">
      <div class="col-lg-6">
        <ul class="list-unstyled">
          <li><a href="#">Category Name</a>
          </li>
          <li><a href="#">Category Name</a>
          </li>
          <li><a href="#">Category Name</a>
          </li>
          <li><a href="#">Category Name</a>
          </li>
        </ul>
      </div>
      <!-- /.col-lg-6 -->
      <div class="col-lg-6">
        <ul class="list-unstyled">
          <li><a href="#">Category Name</a>
          </li>
          <li><a href="#">Category Name</a>
          </li>
          <li><a href="#">Category Name</a>
          </li>
          <li><a href="#">Category Name</a>
          </li>
        </ul>
      </div>
      <!-- /.col-lg-6 -->
    </div>
    <!-- /.row -->
  </div>

  <!-- Side Widget Well -->
  <div class="well">
    <h4>Side Widget Well</h4>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Inventore, perspiciatis adipisci accusamus laudantium odit aliquam repellat tempore quos aspernatur vero.</p>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>kwaaaaa</title>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= csrf_meta_tags %>
  </head>
  <body>

  <%= render 'layouts/header' %>
  <div class='container'>
    <%= yield %>
  </div>
  <%= render 'layouts/footer' %>

  </body>
</html>

app/views/posts/index.html.erb
<h1>你好</h1>

<div ng-controller="PostController">

  <!-- Page Content -->
  <div class="container">

    <div class="row">

      <!-- Blog Entries Column -->
      <div class="col-md-8">

        <h1 class="page-header">
          Page Heading
          <small>Secondary Text</small>
        </h1>

        <!-- First Blog Post -->


        <%= react_component 'Posts', { posts: @posts } %>
        


      </div>
      <!-- Blog Sidebar Widgets Column -->
      <div class="col-md-4">
        <%= render 'layouts/sidebar' %>
      </div>

    </div>
    <!-- /.row -->

    <hr>

  </div>
  <!-- /.container -->

</div>

app/views/posts/show.html.erb
  <div class="row">
    <!-- Blog Post Content Column -->
    <div class="col-lg-8">
      <!-- Blog Post -->
      <!-- Title -->


      <%= react_component 'Post', { post: @post } %>


      <!--<h1>{{post.title}}</h1>-->

      <!--&lt;!&ndash; Author &ndash;&gt;-->
      <!--<p class="lead">-->
        <!--by <a href="#">Start Bootstrap</a>-->
      <!--</p>-->

      <!--<hr>-->
      <!--&lt;!&ndash; Date/Time &ndash;&gt;-->
      <!--<p><span class="glyphicon glyphicon-time"></span> Posted on August 24, 2013 at 9:00 PM</p>-->

      <!--<hr>-->
      <!--&lt;!&ndash; Preview Image &ndash;&gt;-->
      <!--<img class="img-responsive" src="http://placehold.it/900x300" alt="">-->

      <!--<hr>-->

      <!--&lt;!&ndash; Post Content &ndash;&gt;-->
      <!--<p class="lead">{{ post.body }}</p>-->
      <!--<hr>-->

      <!--<div ng-controller="CommentController">-->
        <!--<div ng-show="comments.$resolved && comments.length == 0">-->
          <!--<h4>There's nothing here...</h4>-->
          <!--<p>Be the first to comment on this post below!</p>-->
        <!--</div>-->

         Blog Comments
        <div ng-repeat="comment in comments">
          <!-- Comment -->
          <div class="media">
            <a class="pull-left" href="#">
              <img class="media-object" src="http://placehold.it/64x64" alt="">
            </a>
            <div class="media-body">
              <h4 class="media-heading">{{comment.title}}
                <small>August 25, 2014 at 9:30 PM</small>
                <small><a class="glyphicon glyphicon-trash" ng-click="deleteComment($index)" href=""></a></small>
              </h4>
              {{ comment.body }}
            </div>
          </div>
          <br>
        </div>

        <!-- Comments Form -->
        <div class="well">
          <h4>Leave a Comment:</h4>
          <form role="form" ng-submit="addComment()">
            <div class="form-group">
              <input type="text" class="form-control" ng-model="newComment.title" rows="3" required/>
              <textarea class="form-control" ng-model="newComment.body" rows="3" required></textarea>
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
          </form>
        </div>
        <hr>
      </div>

    <div class="col-md-4">
      <%= render 'layouts/sidebar' %>
    </div>


    </div>
    <!-- Blog Sidebar Widgets Column -->